# Themes and word lists
THEMES = {
    "animals": ["elephant", "tiger", "kangaroo", "penguin", "dolphin", "giraffe", "octopus", "crocodile", "panda", "wolf"],
    "fruits": ["apple", "banana", "cherry", "grape", "pineapple", "mango", "strawberry", "blueberry", "watermelon", "peach"],
    "countries": ["france", "brazil", "canada", "japan", "germany", "italy", "russia", "mexico", "india", "egypt"],
    "instruments": ["guitar", "piano", "violin", "drums", "flute", "saxophone", "trumpet", "harp", "cello", "clarinet"],
    "planets": ["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune", "pluto", "ceres"],
}

# Clues dictionary
CLUES = {
    "elephant": {"vague": "This animal is known for its size.", "helpful": "It has a trunk and large ears."},
    "tiger": {"vague": "A strong and fast predator.", "helpful": "It has stripes and is part of the big cat family."},
    "kangaroo": {"vague": "An animal that hops.", "helpful": "It carries its young in a pouch."},
    "penguin": {"vague": "A bird that cannot fly.", "helpful": "It lives in cold regions and waddles."},
    "dolphin": {"vague": "A marine creature.", "helpful": "It is highly intelligent and friendly."},
    "giraffe": {"vague": "A tall animal.", "helpful": "It has a long neck and feeds on tree leaves."},
    "octopus": {"vague": "A sea creature.", "helpful": "It has eight arms and can squirt ink."},
    "crocodile": {"vague": "A reptile that swims.", "helpful": "It has sharp teeth and lives in rivers."},
    "panda": {"vague": "A black and white animal.", "helpful": "It mainly eats bamboo."},
    "wolf": {"vague": "A wild canine.", "helpful": "It hunts in packs."},
    
    "apple": {"vague": "A commonly eaten fruit.", "helpful": "It is often associated with health and teachers."},
    "banana": {"vague": "A yellow fruit.", "helpful": "It is curved and easy to peel."},
    "cherry": {"vague": "A small red fruit.", "helpful": "It often comes in pairs with a stem."},
    "grape": {"vague": "A small round fruit.", "helpful": "It grows in bunches on vines."},
    "pineapple": {"vague": "A tropical fruit.", "helpful": "It has spiky skin and sweet yellow flesh."},
    "mango": {"vague": "A tropical fruit.", "helpful": "It has a large pit and sweet orange flesh."},
    "strawberry": {"vague": "A red fruit.", "helpful": "It has tiny seeds on the outside."},
    "blueberry": {"vague": "A small blue fruit.", "helpful": "It is often used in muffins and pancakes."},
    "watermelon": {"vague": "A large fruit.", "helpful": "It has a green rind and red juicy flesh."},
    "peach": {"vague": "A fuzzy fruit.", "helpful": "It has a pit and sweet flesh."},
    
    "france": {"vague": "A European country.", "helpful": "It is famous for its wine and the Eiffel Tower."},
    "brazil": {"vague": "A South American country.", "helpful": "It is known for Carnival and soccer."},
    "canada": {"vague": "A country known for its nature.", "helpful": "It has a maple leaf on its flag."},
    "japan": {"vague": "An Asian country.", "helpful": "It is known for sushi and cherry blossoms."},
    "germany": {"vague": "A European country.", "helpful": "It is known for its beer and castles."},
    "italy": {"vague": "A European country.", "helpful": "It is famous for pizza and pasta."},
    "russia": {"vague": "A large country.", "helpful": "It spans two continents, Europe and Asia."},
    "mexico": {"vague": "A North American country.", "helpful": "It is known for tacos and mariachi music."},
    "india": {"vague": "A South Asian country.", "helpful": "It is known for its spices and Bollywood."},
    "egypt": {"vague": "A North African country.", "helpful": "It is famous for the pyramids."},
    
    "guitar": {"vague": "A musical instrument.", "helpful": "It has strings and is often used in bands."},
    "piano": {"vague": "A keyboard instrument.", "helpful": "It has black and white keys."},
    "violin": {"vague": "A string instrument.", "helpful": "It is played with a bow."},
    "drums": {"vague": "A percussion instrument.", "helpful": "It is played by striking with sticks."},
    "flute": {"vague": "A woodwind instrument.", "helpful": "It is played by blowing across a hole."},
    "saxophone": {"vague": "A brass instrument.", "helpful": "It is often used in jazz music."},
    "trumpet": {"vague": "A brass instrument.", "helpful": "It is played by blowing into a mouthpiece."},
    "harp": {"vague": "A string instrument.", "helpful": "It is plucked with fingers."},
    "cello": {"vague": "A string instrument.", "helpful": "It is larger than a violin and has a deeper sound."},
    "clarinet": {"vague": "A woodwind instrument.", "helpful": "It uses a reed to produce sound."},
    
    "mercury": {"vague": "A planet in the solar system.", "helpful": "It is the closest to the Sun."},
    "venus": {"vague": "A planet in the solar system.", "helpful": "It is known as Earth's twin."},
    "earth": {"vague": "Our home planet.", "helpful": "It has life and oceans."},
    "mars": {"vague": "A red planet.", "helpful": "It is known as the Red Planet."},
    "jupiter": {"vague": "A large planet.", "helpful": "It is the largest in the solar system."},
    "saturn": {"vague": "A gas giant.", "helpful": "It has prominent rings."},
    "uranus": {"vague": "A distant planet.", "helpful": "It rotates on its side."},
    "neptune": {"vague": "A blue planet.", "helpful": "It is the farthest in the solar system."},
    "pluto": {"vague": "A dwarf planet.", "helpful": "It was once considered the ninth planet."},
    "ceres": {"vague": "A dwarf planet.", "helpful": "It is located in the asteroid belt."}
}